[package]
name = "png2paltex"
version = "0.1.0"
edition = "2024"

[dependencies]
png = "0.17.16"
bang_core = { path = "../../bang_core" }
paltex = { path = "../../libs/paltex", features = ["encoding"] }
